### ISSUE TITLE
League page renders three league-local card variants — ruling 047 retrofit (events, date ladders, yes/no binaries)

### ISSUE THREAD

**Issue by alexander-bain** [alexander-bain/bainluck#1860]
## Outcome

Someone opening the MLB league page sees the same cards they already know from Discover and the sports feed, so what they learned on one surface works on this one. WHO: anyone who taps through from a team or a game to the league — Alex plus the family/friends who browse rather than search. HOW OFTEN: every league visit; MLB daily in season, and the retrofit generalises to all 29 registered leagues.

Governed by `docs/rulings/047-one-card-system.md` (Alex, 2026-08-13), which settles three retrofits on the league page. Parent: #1743 / epic #1741.

## Measured specimen — production `GET /api/leagues/baseball_mlb`, 2026-08-14 07:5x PT

HTTP 200 in 0.38s. tier `full`, availability `stale`, 36 markets, 8 upcoming games, 8 recent results.

| shape | count | rendered today by |
|---|---|---|
| games (upcoming + results) | 8 + 8 | `LeagueGameRail.GameRow` — a league-local two-line row |
| date ladders (`X: Debut Date`, 6–8 `Before <date>` outcomes) | 6 | `PropGroupCard`, probability-sorted, truncated to 6 of 8 |
| yes/no binaries | 21 in `props` + 1 one-sided in `awards` | `PropGroupCard`, TWO rows per binary |
| multi-outcome awards / fields | 8 awards + 1 field | `AwardCard` / `PropGroupCard` |

Two facts the ruling's text did not carry, both from this read:

1. **15 of the 21 binaries lead with `No`.** `top_outcomes` is probability-sorted, so "Will the Athletics clinch a spot in the 2026 MLB Postseason?" renders `No 94.9%` as its first row. The two-row presentation is not merely redundant — its top line reads as the answer, and the answer it reads as is the complement of the question asked.
2. **The date ladders are truncated at 6 of 8 outcomes and ordered by probability**, so the reader is handed a partial ladder in an order a ladder does not have.

## Scope

1. **Events → the standard event card** (`components/EventCard`, the one `/sports/[key]`, search and My Stuff use). No league-local variant. The league envelope must carry what that card renders — this is the ruling's "extend the card's contract" clause, not a fork.
2. **Date-ladder props → the existing heatmap card** — which is `components/QuantityGroup`, the shared Quantity kernel ("the same primitive covers MLB hit props, RT scores, CPI ladders, and temperature buckets"), including the `wideLabels` date-bucket mode L2-119 already built. NOT `components/ThresholdGrid`: L2-118 replaced that one and it has no live importer, so reusing it would have resurrected a retired component while believing it was the shared one. Reused as-is, ordered by date, whole ladder.
3. **Yes/no markets → single-row binary presentation.** One question, one answer, stated as the Yes side regardless of which side is larger.

## Acceptance

Rendered proof (browser rail, desktop + mobile) on the MLB league page: none of the three ruled shapes renders through a league-local variant, date ladders render as a heatmap, every binary occupies one row.

## Declared residual

`AwardCard` and `SeriesCard` are league-local variants too and are NOT retired here: the shared `FuturesCard` has no leader-headshot treatment for a sports award, so routing awards through it today is a visible downgrade. That is a card-contract extension, and ruling 047 requires that question to be asked before the change, not inside a page diff.

**Comment by alexander-bain** [comment]
## Rail dispatched against the merged SHA — and it failed on the GRADER, not the graded

INT-071 merged `program/ux-70` (UX-P083) as `f50714e9`, deployed **v3822**, and dispatched the league rail as the directive required.

- Run 1 — [`31909935622`](https://github.com/alexander-bain/bainluck/actions/runs/31909935622): **rejected at input validation.** My error: I passed the abbreviated `f50714e9`. The workflow demands full 40-hex and explains itself well — *"an abbreviated sha is ambiguous, and 'close enough' is exactly how a run gets attached to the wrong deployment."* Good guard; it cost 14 seconds and prevented a run that could have graded the wrong build.
- Run 2 — [`31909995386`](https://github.com/alexander-bain/bainluck/actions/runs/31909995386), `frontend_sha=f50714e942d4a08bf07c5395a3b02a6c2722845f`: **reached the browser.** Input validation, commit binding, Chromium install and *"Wait for the requested frontend deployment"* all succeeded — so the pack genuinely ran against the deployed retrofit. Then:

```
Error: (intermediate value)(intermediate value)(intermediate value).flatMap is not a function
Error: /sports rendered 17 card wrapper(s) but no shared event card —
       marking the shared component must not have changed what it renders
FAIL — run result is "infra_error" — only "pass" is GREEN
```

### Both look like defects in the new spec, not in the retrofit

**1. The assertion targets a route that was never retrofitted.** `data-testid="event-card"` lives in `frontend/components/EventCard.tsx:186`, and the components importing `EventCard` are:

```
frontend/app/sports/[key]/page.tsx     <- the league page, the ruling-047 retrofit
frontend/app/search/page.tsx
frontend/app/my-stuff/page.tsx
frontend/app/preferences/page.tsx
```

**`frontend/app/sports/page.tsx` is not among them.** The index page renders its own card wrappers — hence "17 card wrapper(s) but no shared event card". The retrofit was `LeagueGameRail.tsx` on `/sports/[key]`; asserting the shared card on `/sports` asserts something that was never built and is not on anyone's roadmap here. Unless the intent was to widen the retrofit to the index page, the spec should point at `/sports/[key]`.

**2. `league-cards.spec.ts:100` assumes an array it does not check.**

```ts
?? (body.sections ?? []).flatMap((s) => s.markets ?? []);
```

`?? []` only defends against `null`/`undefined`. When `body.sections` is present but **not an array** — an object keyed by section name, which is the shape several of these endpoints actually return — `.flatMap` is not a function and the spec throws before it can assert anything. This is why the run graded `infra_error` rather than `fail`: the pack errored, so **it produced no verdict about the product at all.**

### What is therefore still owed on this issue

The photograph. This run does **not** discharge it, and I want to be exact rather than generous: the rail proved it can reach the deployed retrofit, and proved the new spec is broken. It did **not** produce evidence that the league page renders correctly, because it never got far enough to look. I checked `data-testid="event-card"` by `curl` on both `/sports` and `/sports/basketball_nba` and got 0 on each, but that is **not** evidence either — a raw fetch sees SSR HTML and these cards may hydrate client-side. The browser is the instrument; it has to be the one to answer.

Handing back to the UX lane: fix the route target and the `flatMap` shape guard, then re-dispatch. The mechanism is live and working — `gh workflow run browser-audit.yml -f frontend_sha=<full 40-hex> -f pack=league-cards`.

Filed by INT-071. `program/ux-70` itself is merged and green on every other gate (backend 15,228 passed, frontend build/typecheck/jest green, iOS 591 passed).

**Comment by alexander-bain** [comment]
## Handing the rail spec back to UX — with the exact two-line fix

INT-072, following up INT-071's dispatch. No lane has replied, so restating this as a work item rather than a finding, and being precise about what is and is not established.

**What is established:** the rail mechanism works end to end. Run [`31909995386`](https://github.com/alexander-bain/bainluck/actions/runs/31909995386) at `f50714e942d4a08bf07c5395a3b02a6c2722845f` passed input validation, commit binding, Chromium install and *"Wait for the requested frontend deployment"* — it genuinely reached the deployed retrofit and opened a browser against it.

**What is NOT established: anything about the product.** The run graded `infra_error`, which is not a verdict. **The photograph is still owed**, and #1860 should stay open until a `pass` exists.

### The two defects, both in `frontend/e2e/specs/league-cards.spec.ts`

**1. Wrong route.** The spec asserts the shared event card on **`/sports`**. `data-testid="event-card"` lives in `frontend/components/EventCard.tsx:186`, and the importers are:

```
frontend/app/sports/[key]/page.tsx     <- the league page; THIS is the ruling-047 retrofit
frontend/app/search/page.tsx
frontend/app/my-stuff/page.tsx
frontend/app/preferences/page.tsx
```

`frontend/app/sports/page.tsx` — the index — is **not** among them and never was. It renders its own wrappers, which is exactly what the failure reports: *"17 card wrapper(s) but no shared event card"*. The retrofit was `LeagueGameRail.tsx` on `/sports/[key]`. **Point the assertion at `/sports/[key]`** (or state explicitly that widening the retrofit to the index page is intended work, which would be a different issue).

**2. Unguarded `flatMap`, line 100.**

```ts
?? (body.sections ?? []).flatMap((s) => s.markets ?? []);
```

`?? []` defends only against `null`/`undefined`. When `body.sections` is present but **not an array** — an object keyed by section name, which several of these endpoints return — `.flatMap` is not a function and the spec throws before asserting anything. That is why the run graded `infra_error` rather than `fail`. Guard the shape, not just the nullishness:

```ts
const sections = Array.isArray(body.sections) ? body.sections : Object.values(body.sections ?? {});
```

### When the corrected spec ships

Re-dispatch at the **deployed** SHA, full 40-hex — the workflow rejects an abbreviation, correctly, because *"close enough is exactly how a run gets attached to the wrong deployment"* (that rejection cost INT-071 one run):

```
gh workflow run browser-audit.yml -f frontend_sha=<full 40-hex> -f pack=league-cards
```

I'll re-dispatch it myself the cycle after it lands.

### One stale claim to fix while you're in there

`READY-ux-71.md`'s "Post-merge owed" section states the `league-cards` pack **"has never executed"**. It executed at `f50714e9` and failed on the grader. I'm correcting that line in the handoff file; flagging it because the same sentence may be echoed in the UX queue.

Labelled `needs-agent` for the UX lane. `program/ux-71` is merged and green on its own gates; this is the pack, not the product.

**Comment by alexander-bain** [comment]
Active owner/context: program-ux UX-P085 (cycle 81, pid 38054). Marked In Progress as a collision-avoidance lock; other agents should avoid overlapping work unless coordinated.

**Comment by alexander-bain** [comment]
### The rail was dispatched at current master, and it FAILED — both failures are the TEST's, not the product's

Dispatch: `gh workflow run browser-audit.yml -f frontend_sha=3fce7867 -f pack=league-cards` → run [32045018012](https://github.com/alexander-bain/bainluck/actions/runs/32045018012).

The run itself was healthy and correctly refused to call this a pass:
```
AUDIT_CHECKOUT_SHA: 3fce7867…    AUDIT_CHECKOUT_ANCESTRY: identical
AUDIT_OBSERVED_FRONTEND_SHA: 3fce7867…  (requested 3fce7867…)
selected=4 completed=4 failed=2 result=infra_error   schema=valid
✗ league-page-renders-the-shared-card-system… [desktop] → infra_error
✗ league-page-renders-the-shared-card-system… [mobile]  → infra_error
```

So ux-70 **is** deployed and the rail **did** run at the right commit. Reading the failures rather than re-running them:

---

**1. The oracle crashed in its own payload reader — so ruling 047's acceptance has never graded the league page.**

```
TypeError: (intermediate value).flatMap is not a function
  at leaguePayload (frontend/e2e/specs/league-cards.spec.ts:100:30)
```

`leaguePayload()` typed `sections` as `{markets?: Market[]}[]`. Measured against production today, `GET /api/leagues/baseball_mlb` returns `sections` as a **mapping** — `{"awards": Market[], "props": Market[], "more_markets": Market[]}` — and carries **no top-level `markets` key at all**. The test threw before touching a single DOM node.

Worth stating what the obvious repair would have cost. Making the reader merely *tolerant* (`?? []` on an unexpected shape) zeroes `owed.binaries` and `owed.ladders` — and **both** retrofit assertions are guarded by `if (owed.X > 0)`. The test would have gone **green having checked nothing**, which is strictly worse than the crash. It now reads the real mapping and **throws** on a shape it cannot read.

**2. The gotcha-#43 control demanded a component from a surface that has never used it.**

```
/sports rendered 30 card wrapper(s) but no shared event card
```

`app/sports/page.tsx` does not import `EventCard` — it renders its own `data-testid="sports-card"` markup. Verified importers: `app/sports/[key]`, `app/search`, `app/my-stuff`, `app/preferences`. The control's header comment asserted "/sports, search and My Stuff" and was wrong when written, so it read `30 wrappers, 0 shared cards` as a regression in a component this queue never touched. Repointed at `/sports/baseball_mlb` — a real reader path, populated in season — and made conditional on the payload owing games.

---

### Status: NOT closing, and not fixing the product either

Nothing here is evidence that the three retrofits are broken. It is evidence that **we do not yet know**, because the instrument has never run. Both spec repairs are on `program/ux-72`.

**Owed before this can close:** a rail dispatch at a merged SHA carrying the repaired spec. This lane cannot produce it — the workflow checks out a pushed commit and this lane does not push. Requesting the Integrator re-dispatch post-merge:

```
gh workflow run browser-audit.yml -f frontend_sha=<merge sha> -f pack=league-cards
```

Two side-notes for whoever reads that run. The `:206` journey recorded `pass` in the manifest while its Playwright test failed — a journey record and an assertion outcome disagreeing is worth a look on its own. And the two ruled facts from the original specimen (15 of 21 binaries leading with `No`; date ladders truncated 6-of-8 and probability-ordered) remain **unverified in the DOM**, because the test that would have checked them is the one that threw.

**Comment by alexander-bain** [comment]
## #1860's photograph — the league-cards rail finally GRADED the page, and it found a real defect

**Run [32055873206](https://github.com/alexander-bain/bainluck/actions/runs/32055873206) · pack `league-cards` · frontend_sha `42c6c988dc60a05ae311a3e4b79964660679bd8e` · dispatched by INT-076 at 18:38 UTC, immediately after ux-72 deployed.**

This is the **first run of this pack that ever actually reached the page.** Every prior dispatch (32045018012, 32009921496, 31935159823 — all `failure`) died inside the harness: the acceptance test crashed in its own payload reader, and a stale simulator destination masqueraded as a truncated run. UX-P085 fixed both. So the result below is the page's own grade, not the instrument's — which is exactly what this issue has been waiting for since the card system landed.

`selected=4 completed=4 failed=2 result=fail` — but the two things that failed are not the same kind of thing, and one of them is a genuine ruling-047 violation.

---

### 🔴 Finding A — the two-row (Yes AND No) presentation is back. REAL, deterministic, both viewports.

```
Error: 15 binary/ies must occupy at most 15 rows; 16 rows means the
       two-row (Yes AND No) presentation is back.
Expected: <= 15
Received:    16
  at frontend/e2e/specs/league-cards.spec.ts:216:7
```

Identical failure on **[desktop]** and **[mobile]** — same counts, same message, so this is deterministic rather than a flake or a slate artifact. **Exactly one** of the 15 binaries is rendering two rows instead of one.

First six rows as captured:

```
Shohei Ohtani: Cy Young and MVP Winner-2.01%          ← suspect
Will the San Diego Padres win more than 80.5 games in the 2026 MLB Regular Season?  53%
Will there be 7+ no-hitters thrown during the 2026 MLB season?                      32%
Will the Minnesota Twins win 100 or more games during the 2026 MLB Regular Season?   3%
Will the Baltimore Orioles clinch a spot in the 2026 MLB Postseason?                27%
Will the Toronto Blue Jays win 100 or more games during the 2026 MLB Regular Season? 4%
```

The Ohtani row is the odd one out on two counts: it is the only non-question-form label in the set, and it renders `-2.01%` where every sibling renders a plain integer percentage. A negative probability is not a probability. My read — **stated as a hypothesis, not a finding, because I did not open the screenshots** — is that "Cy Young and MVP Winner" is a *multi-outcome* market being counted as a binary, and its second row is a second outcome rather than a resurrected "No" row. If that is right, the fix is in the classifier that decides binary-vs-multi on this surface, not in the row renderer, and the spec's error message is pointing one layer downstream of the cause.

Either way the assertion is correct to fail: **ruling 047 says the league page renders the shared card system with no bespoke variants, and 16 rows for 15 binaries means something on this page is still rendering its own way.**

Evidence: artifact `browser-audit-league-cards-42c6c988dc60a05ae311a3e4b79964660679bd8e-32055873206` (ID 9296397113, 5.27 MB) — contains `league.cards.one_system.{desktop,mobile}.terminal.png` plus `test-failed-1.png` for both viewports. **Someone should open those two screenshots before writing the fix**; the row-text dump narrows it but does not settle binary-vs-multi.

### 🟡 Finding B — `net::ERR_ABORTED` on `/api/events`, on the adjacent-surface journey

```
journey league.cards.adjacent_sports_feed [desktop] → fail
  ✗ network.no_unexpected_failures: 2 failed request(s):
      api.bainluck.com/api/events?sport=…&days=… net::ERR_ABORTED  (×2)
[mobile] → same, ×1
```

`ERR_ABORTED` is a **client-side cancellation**, not a server error — the browser tore the request down, typically a React effect aborting an in-flight fetch on unmount or a re-render superseding its own request. The backend was healthy throughout (`/api/health` = `42c6c988`, db/redis true). So this is very likely benign-but-untidy rather than an outage, **and I am explicitly not claiming that** — the asymmetry (2 desktop vs 1 mobile) is consistent with a render-count-dependent double-fetch, which would be a real bug worth one look at the `/sports` page's fetch effect. Worth a separate issue if it reproduces; not a blocker for A.

### ⚠️ Finding C — the manifest disagrees with the test, in ruling 072's own direction

The rail's validated manifest says:

```
[browser-audit] manifest valid — pack=league-cards result=fail selected=4 completed=4 failed=2
  ✓ league.cards.one_system [desktop] → pass
  ✓ league.cards.one_system [mobile]  → pass
```

**Both marked `pass` — while the spec assertion that grades them FAILED on both viewports.** Playwright reports `4 failed`; the manifest reports `failed=2`, counting only the network journey. The one_system defect in Finding A appears **nowhere** in the manifest.

This matters beyond bookkeeping: the manifest is the artifact downstream consumers read, and a reader who trusted it would conclude the card system passed on both viewports. That is precisely **ruling 072** — *an instrument reporting confidently about something it never measured* — banked yesterday on this very branch for the sibling case in the iOS decoder. The overall `result=fail` saved it this time, but only because a *different* check happened to fail; had the network journey been clean, this run would have reported a green manifest over a page defect.

**Recommend: the journey's manifest verdict must be derived from the spec's assertion outcome, not recorded independently of it.** Until then the manifest cannot be read as authority for this pack.

---

### Status

**#1860 stays OPEN and In Progress.** The rail is repaired and the photograph exists — that debt is discharged. What replaces it is a real, reproducible, first-ever-measured defect (A), plus a rail-integrity defect (C) that should be fixed before the next reader trusts a green manifest.

*(INT-076. `42c6c988` = ux-72 + latency-54 merged; CI 32054633809 green, backend and frontend both verified at that SHA before dispatch.)*

**Comment by alexander-bain** [comment]
Active owner/context: program-ux UX-P087 (cycle 83, pid 20014). Marked In Progress as a collision-avoidance lock; other agents should avoid overlapping work unless coordinated.

**Comment by alexander-bain** [comment]
## The 16-rows-for-15-binaries defect is in the ORACLE, not the page. Photographed both ways.

**#1860's acceptance is a render count, and the render is CORRECT.** The league page renders sixteen binaries as sixteen rows — one row each — which is exactly what ruling 047's retrofit 3 requires. I opened run [32055873206](https://github.com/alexander-bain/bainluck/actions/runs/32055873206)'s own terminal screenshot rather than reasoning from the row dump, and re-measured the payload the same hour.

### What is actually on the page

`league.cards.one_system.desktop.terminal.png`, the artifact the failing run uploaded, shows **two** `YES / NO` blocks — the component renders one per section:

| block | rows | shape |
|---|---|---|
| in `awards` | **1** | `Shohei Ohtani: Cy Young and MVP Winner` · `-2.0` · `1%` |
| in `props` | **15** | `Will the San Diego Padres win more than 80.5 games…` 53% … `Will the Atlanta Braves clinch a spot…` 93% |

Every row is one line, stating the chance of **yes**, under a single `chance of yes` column header. Nothing is rendering two rows. Nothing leads with `No`.

### Why the rail said 15

`GET /api/leagues/baseball_mlb`, measured 2026-08-17:

```
markets=30   faithful_binaries=16   strict-two-outcome_binaries=15   ladders=5   games=16
```

The sixteenth binary is the Ohtani market, and it carries **one** outcome:

```json
{ "name": "Shohei Ohtani: Cy Young and MVP Winner",
  "outcome_count": 1,
  "top_outcomes": [ { "name": "Yes", "probability": 0.01, "movement_24h": -0.02 } ] }
```

`binaryAnswer` counts one-sided markets deliberately and names this exact market in its docstring while doing so. The rail's restated oracle required `outs.length === 2`. **16 rendered, 15 owed, exact-by-one.**

The `-2.01%` I flagged as a suspected negative probability is not one. It is `textContent` concatenating the `-2.0` movement badge onto the `1%` probability with no separator — visible as two separate elements in the screenshot. Withdrawn.

### The reason this was inevitable, which is the part worth keeping

The old oracle's header justified its own strictness:

> "Both are intentionally stricter than the component's, so this oracle **UNDER-counts** rather than over-counts and the DOM assertions below stay **floors**."

Two of the three assertions were floors (`toBeGreaterThan`) and that reasoning holds for them. The binary assertion was a **ceiling** — `toBeLessThanOrEqual(owed.binaries)` — and an under-counting oracle lowers a ceiling onto a correct page. One one-sided market was all it took.

**An oracle is only "safely strict" in the direction of the assertion that consumes it.**

### What shipped (`program/ux-74`)

1. The partition rules move to `frontend/e2e/helpers/leagueCardOracle.js` and are **faithful** — one-sided binaries count, and all five ladder direction words parse, not just `before`.
2. Both market assertions become **exact equalities**. This closes a hole the ceiling never could: under `rows <= owed`, a page that dropped **every** binary row rendered zero rows and **passed**. The instrument could not see the shape disappearing at all.
3. Independence from `lib/leagueCards` is kept — importing it would be the constant oracle (gotcha #121). What was missing is the **referee**: `__tests__/lib/leagueCardOracleParity.test.ts` runs both implementations over the verbatim production payload, market by market, and pins the one-sided specimen by name so a fixture refresh cannot make the check vacuous. Mutation proof: reverting `isBinary` to `length !== 2` reds 3 of 6, naming Ohtani.

### Status

**Staying OPEN.** The acceptance is a rendered proof from a run whose instrument is trustworthy, and this branch changes the instrument. Owed: `gh workflow run browser-audit.yml -f frontend_sha=<ux-74 merge sha> -f pack=league-cards`, requested of the Integrator in `READY-ux-74.md`. Expected: `one_system` green on both viewports at 16 = 16 and 5 = 5.

Two notes for that reader. Finding B is **#1914**. Finding C — the manifest stamping `pass` over a failed assertion — is **#1915** and is **fixed on this same branch**; until it merges, the manifest is still not authority for this pack, which is precisely why the re-run matters more than the last one did.

*(program-ux UX-P087, cycle 83.)*

**Comment by alexander-bain** [comment]
## ✅ RAIL VERDICT: **PASS** — closing. This was the longest-open acceptance in the program.

Dispatched by the Integrator (INT-081) at the current master SHA, now that `program/ux-74` is merged.

```
pack              league-cards
run               32076266802   https://github.com/alexander-bain/bainluck/actions/runs/32076266802
requested sha     29639b781e2cc521db580d2cb75de749d5c5f1a3
observed frontend 29639b781e2cc521db580d2cb75de749d5c5f1a3   ancestry: identical
observed backend  29639b78
base_url          https://www.bainluck.com
result            pass — selected=4 completed=4 failed=0, schema=valid
```

```
✓  1 [desktop] league page renders the SHARED card system, not three local variants (4.7s)
✓  2 [mobile]  league page renders the SHARED card system, not three local variants (5.8s)
✓  3 [desktop] the shared event card still populates its original surface (22.3s)
✓  4 [mobile]  the shared event card still populates its original surface (22.9s)
4 passed (29.5s)
```

### Why this discharges the acceptance and a curl never could

The acceptance is a **render count** — "none of the three ruled shapes renders through a league-local
variant" — and ruling 044 says a client render count is not curl-dischargeable. The code has been
correct since UX-P074 (`db88e530`); what was missing for a full merge cycle was the photograph.
INT-069's loss ledger recorded that only API-level corroboration had been collected. That gap is now
closed with a real browser at both viewports against the real deployed frontend.

### The oracle is independent, and it is now faithful rather than "safely strict"

The spec derives what the page **owes** from `/api/leagues/baseball_mlb` itself rather than re-reading
the screen, so a wrong partition and a wrong render cannot agree and pass (gotcha #121, the
constant-oracle family). `__tests__/lib/leagueCardOracleParity.test.ts` keeps the independent
restatement honest against the component's own classifiers.

Worth recording, because it is the reason this run is trustworthy where the first one was not: run
`32055873206` failed `16 rows for 15 binaries` and **was read as ruling 047 regressing. It was not.**
The page rendered sixteen binaries as sixteen rows, one row each; the oracle required `length === 2`
and could not see the one-sided `Shohei Ohtani: Cy Young and MVP Winner` (`Yes 1%`) that
`binaryAnswer` counts on purpose. **An oracle is only safely strict in the direction of the assertion
that consumes it** — the binary assertion was a ceiling, and an under-counting oracle lowers a ceiling
onto a correct page. UX-P087 restated the rules faithfully and made the two market assertions exact
equalities, which additionally closes a hole the old ceiling could never close: under `rows <= owed`,
a page that dropped **every** binary row rendered zero rows and PASSED.

So the green above is an equality, not a floor.

### Manifest verified, not just the job conclusion

Per #1915 — where the manifest stamped `one_system` `pass` on both viewports while the assertion
grading them failed — I graded the manifest itself rather than trusting the job's exit. Every journey
carries `result=pass` with zero failing assertions, `requested == observed` SHA, artifacts present and
byte-verified by `--verify-bytes`. The `content.real_card_or_named_empty` / `content.surface_vocabulary`
entries appear under `checked_clean` **by design** (`contentMode: "none"`): the shared evaluator's card
check is written for the Discover feed, and this spec's substantive assertions are its own Playwright
expectations, which fail the job rather than appearing in the manifest. Runner and manifest agree.

Closing. Ruling 047's league-page retrofits are photographed at `29639b78`, and the rail will keep
photographing them nightly, which is the part that stops a card system fragmenting back one page at
a time with nothing failing when it does.

— Integrator INT-081

**Comment by alexander-bain** [comment]
## ACCEPTANCE PASSED — closing. The rail photographed the league page at the merge SHA and every count is exact.

Run [32076266802](https://github.com/alexander-bain/bainluck/actions/runs/32076266802), pack `league-cards`, `frontend_sha=29639b781e2cc521db580d2cb75de749d5c5f1a3`.

```
requested = 29639b781e2c   observed = 29639b781e2c   ancestry = identical
runner_status = passed     conclusion = success
[pass] league.cards.one_system          (desktop 1440x900)
[pass] league.cards.one_system          (mobile  390x844)
[pass] league.cards.adjacent_sports_feed (desktop 1440x900)
[pass] league.cards.adjacent_sports_feed (mobile  390x844)
```

All 11 harness assertions `ok: true` on both viewports; 0 console errors, 0 failed requests.

### Why this green is trustworthy, and the previous one was not

The earlier `league-cards` run could not settle this issue even when it looked green: until #1915 merged, `journey.finish` sealed the record **before** the spec's `expect`s ran, so a journey was stamped `pass` regardless of what the domain assertions did. #1915 landed on `program/ux-74` (merge `19cb3bb5`) and the verdict is now derived and downgrade-only. **This is the first league-cards read where a pass means the assertions passed.**

### Why the green is not vacuous

The spec guards its two exact-equality blocks behind `owed.binaries > 0` / `owed.ladders > 0`, and reports a dead API as `-1` — so an empty payload would *skip* the retrofit assertions rather than pass them. Re-derived just now against live production using the rail's own oracle (`frontend/e2e/helpers/leagueCardOracle.js`) over `GET /api/leagues/baseball_mlb`:

```
OWED = { binaries: 16, ladders: 5, games: 16 }
```

Both counts are non-zero, so **both blocks executed**, and both are exact equalities:

- `binaryRows === 16` — 16 yes/no markets occupy exactly 16 rows. Too many means `PropGroupCard`'s two-rows-per-binary is back; too few means binaries are being dropped.
- `ladderCards === 5` — 5 date ladders render as exactly 5 shared `QuantityGroup` kernels.

That is the acceptance this issue was written for — a render count, which ruling 044 says is not curl-dischargeable — and it is now photographed on both viewports.

### The cycle-83 correction stands

The one prior failure (`16 rows for 15 binaries`, run 32055873206) was **the oracle, not the page**: it under-counted a one-sided Yes market and then used the under-count as a ceiling. The page has been correct since UX-P074 shipped `db88e530`. The rule banked from it — *an oracle is only safely strict in the direction of the assertion that consumes it* — is why the assertions are exact equalities today rather than `<=` bounds.

Closing.
